### ISSUE TITLE
Exception if program started without any previously downloaded data

### ISSUE THREAD

**Issue by ndegendogo** [ndegendogo/cwa_diagnosis_keys#4]
Traceback (most recent call last):
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/cwa_diagnosis_keys.py", line 156, in <module>
    main()
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/cwa_diagnosis_keys.py", line 26, in main
    check_key_numbers_for_country(country)
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/cwa_diagnosis_keys.py", line 52, in check_key_numbers_for_country
    if not check_key_numbers_for_country_of_day(country, day):
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/cwa_diagnosis_keys.py", line 58, in check_key_numbers_for_country_of_day
    hourly_key_counts = get_hourly_key_counts(country, day)
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/cwa_diagnosis_keys.py", line 145, in get_hourly_key_counts
    return [KeyBundle(filename_for_keys(country, day, hour)).number_of_keys() for hour in range(24)]
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/cwa_diagnosis_keys.py", line 145, in <listcomp>
    return [KeyBundle(filename_for_keys(country, day, hour)).number_of_keys() for hour in range(24)]
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/KeyBundle.py", line 12, in __init__
    data = read_file(path)
  File "/Users/kiri/Documents/Projects/PycharmProjects/cwa_diagnosis_keys/KeyBundle.py", line 66, in read_file
    with open(path, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'DE/2020-12-23/0/export.bin'

**Comment by ndegendogo** [comment]
Analysis: the consistency check of key counts (hourly vs daily files) assumes that for all days all hourly files are available.
However, this assumption is wrong, because the server deletes the hourly files after 14*24 hours.

**Comment by ndegendogo** [comment]
Fixed in commit d71cb46
